import { Facility } from "./types";
import { REAL_HIRA_FACILITIES } from "./realHiraData";

// 실제 서비스 전환 시 이 배열만 공공데이터 API(HIRA/NHIS) 연동 결과로 교체하면 됩니다.
const DEMO_FACILITIES: Facility[] = [
  {
    id: "hsp-001",
    name: "서울행복요양병원",
    facilityType: "NURSING_HOSPITAL",
    dataSource: "mock",
    gradeSource: "HIRA",
    grade: 1,
    address: "서울특별시 강남구 삼성로 428",
    lat: 37.5145,
    lng: 127.0995,
    phone: "02-555-0101",
    establishedYear: 2011,
    updatedAt: "2026-06-01",
    parking: { spots: 32, isFree: true },
    doctorGrade: 1,
    nurseGrade: 1,
    nonCoveredFees: [
      { name: "상급병실료(1인실)", min: 90000, max: 150000 },
      { name: "진단서-일반", min: 15000, max: 20000 },
      { name: "간병비(1일)", min: 70000, max: 90000 },
    ],
    departments: [
      { name: "가정의학과", doctorCount: 2 },
      { name: "신경과", doctorCount: 1 },
      { name: "재활의학과", doctorCount: 1 },
    ],
    staff: {
      generalDoctors: 1,
      specialistDoctors: 4,
      socialWorkers: 2,
      physicalTherapists: 5,
      occupationalTherapists: 2,
      pharmacists: 1,
    },
    facilityStatus: {
      generalBeds: 180,
      upgradeBeds: 20,
      physicalTherapyRooms: 4,
      isolationRooms: 2,
    },
    emergencyRoom: { day: true, night: false },
    equipment: [
      { name: "디지털엑스선촬영장치", count: 1 },
      { name: "초음파영상진단기", count: 2 },
      { name: "전산화단층촬영장치(CT)", count: 1 },
    ],
  },
  {
    id: "hsp-002",
    name: "분당사랑요양병원",
    facilityType: "NURSING_HOSPITAL",
    dataSource: "mock",
    gradeSource: "HIRA",
    grade: 1,
    address: "경기도 성남시 분당구 판교로 235",
    lat: 37.3947,
    lng: 127.1112,
    phone: "031-555-0202",
    establishedYear: 2015,
    updatedAt: "2026-05-20",
    parking: { spots: 45, isFree: true },
    doctorGrade: 1,
    nurseGrade: 2,
    nonCoveredFees: [
      { name: "상급병실료(1인실)", min: 80000, max: 120000 },
      { name: "진단서-일반", min: 10000, max: 15000 },
      { name: "간병비(1일)", min: 65000, max: 85000 },
    ],
    departments: [
      { name: "가정의학과", doctorCount: 2 },
      { name: "정신건강의학과", doctorCount: 1 },
    ],
    staff: {
      generalDoctors: 0,
      specialistDoctors: 3,
      socialWorkers: 2,
      physicalTherapists: 4,
      occupationalTherapists: 1,
      pharmacists: 1,
    },
    facilityStatus: {
      generalBeds: 150,
      upgradeBeds: 10,
      physicalTherapyRooms: 3,
      isolationRooms: 1,
    },
    emergencyRoom: { day: false, night: false },
    equipment: [
      { name: "일반엑스선촬영장치", count: 1 },
      { name: "초음파영상진단기", count: 1 },
    ],
  },
  {
    id: "hsp-003",
    name: "수원한빛요양병원",
    facilityType: "NURSING_HOSPITAL",
    dataSource: "mock",
    gradeSource: "HIRA",
    grade: 2,
    address: "경기도 수원시 영통구 광교로 145",
    lat: 37.2895,
    lng: 127.0587,
    phone: "031-555-0303",
    establishedYear: 2009,
    updatedAt: "2026-04-15",
    parking: { spots: 20, isFree: true },
    doctorGrade: 2,
    nurseGrade: 2,
    nonCoveredFees: [
      { name: "상급병실료(1인실)", min: 60000, max: 100000 },
      { name: "진단서-일반", min: 10000, max: 15000 },
      { name: "간병비(1일)", min: 60000, max: 80000 },
    ],
    departments: [{ name: "가정의학과", doctorCount: 1 }],
    staff: {
      generalDoctors: 1,
      specialistDoctors: 1,
      socialWorkers: 1,
      physicalTherapists: 2,
      occupationalTherapists: 0,
      pharmacists: 1,
    },
    facilityStatus: {
      generalBeds: 90,
      upgradeBeds: 0,
      physicalTherapyRooms: 1,
      isolationRooms: 1,
    },
    emergencyRoom: { day: false, night: false },
    equipment: [{ name: "일반엑스선촬영장치", count: 1 }],
  },
  {
    id: "hsp-004",
    name: "일산참사랑요양병원",
    facilityType: "NURSING_HOSPITAL",
    dataSource: "mock",
    gradeSource: "HIRA",
    grade: 1,
    address: "경기도 고양시 일산동구 중앙로 1275",
    lat: 37.6584,
    lng: 126.7734,
    phone: "031-555-0404",
    establishedYear: 2018,
    updatedAt: "2026-06-10",
    parking: { spots: 38, isFree: true },
    doctorGrade: 1,
    nurseGrade: 1,
    nonCoveredFees: [
      { name: "상급병실료(1인실)", min: 100000, max: 160000 },
      { name: "진단서-일반", min: 15000, max: 20000 },
      { name: "간병비(1일)", min: 75000, max: 95000 },
    ],
    departments: [
      { name: "신경과", doctorCount: 2 },
      { name: "재활의학과", doctorCount: 2 },
    ],
    staff: {
      generalDoctors: 0,
      specialistDoctors: 5,
      socialWorkers: 3,
      physicalTherapists: 6,
      occupationalTherapists: 3,
      pharmacists: 2,
    },
    facilityStatus: {
      generalBeds: 210,
      upgradeBeds: 25,
      physicalTherapyRooms: 5,
      isolationRooms: 3,
    },
    emergencyRoom: { day: true, night: true },
    equipment: [
      { name: "디지털엑스선촬영장치", count: 2 },
      { name: "초음파영상진단기", count: 2 },
      { name: "자기공명영상장치(MRI)", count: 1 },
    ],
  },
  {
    id: "hsp-005",
    name: "부천효도요양병원",
    facilityType: "NURSING_HOSPITAL",
    dataSource: "mock",
    gradeSource: "HIRA",
    grade: 3,
    address: "경기도 부천시 원미구 길주로 210",
    lat: 37.4989,
    lng: 126.7831,
    phone: "032-555-0505",
    establishedYear: 2007,
    updatedAt: "2026-03-28",
    parking: { spots: 15, isFree: true },
    doctorGrade: 3,
    nurseGrade: 3,
    nonCoveredFees: [
      { name: "상급병실료(1인실)", min: 50000, max: 90000 },
      { name: "진단서-일반", min: 10000, max: 10000 },
      { name: "간병비(1일)", min: 55000, max: 75000 },
    ],
    departments: [{ name: "가정의학과", doctorCount: 1 }],
    staff: {
      generalDoctors: 1,
      specialistDoctors: 0,
      socialWorkers: 1,
      physicalTherapists: 1,
      occupationalTherapists: 0,
      pharmacists: 1,
    },
    facilityStatus: {
      generalBeds: 70,
      upgradeBeds: 0,
      physicalTherapyRooms: 1,
      isolationRooms: 0,
    },
    emergencyRoom: { day: false, night: false },
    equipment: [{ name: "일반엑스선촬영장치", count: 1 }],
  },
  {
    id: "nh-001",
    name: "행복한요양원",
    facilityType: "NURSING_HOME",
    dataSource: "mock",
    gradeSource: "NHIS",
    grade: 1,
    address: "서울특별시 서초구 효령로 335",
    lat: 37.4926,
    lng: 127.0146,
    phone: "02-555-0606",
    establishedYear: 2013,
    updatedAt: "2026-05-01",
    parking: { spots: 12, isFree: true },
    capacity: 80,
    currentOccupancy: 74,
    waitlistCount: 3,
    staff: {
      careWorkers: 42,
      nurses: 6,
      socialWorkers: 2,
      physicalTherapists: 2,
    },
    staffDetail: {
      administrative: { facilityHead: 1, officeManager: 1, staff: 2 },
      socialCare: { socialWorkers: 2, physicalTherapists: 2, occupationalTherapists: 1 },
      medical: { fullTimeDoctors: 0, partTimeDoctors: 1, nurses: 6, nursingAssistants: 2 },
    },
    roomTypes: ["4인실", "2인실", "1인실"],
    facilityRooms: {
      bedrooms: { single: 4, double: 10, triple: 0, quad: 8, special: 1 },
      medical: { nursingRoom: 1, rehabRoom: 1 },
      dining: { diningRoom: 1, restroom: 6, bathroom: 2 },
    },
    nonCoveredFees: [
      { name: "식재료비(간식제외)", monthly: 450000, daily: 15000 },
      { name: "간식비용", monthly: 60000, daily: 2000 },
    ],
    evaluationDetail: {
      evaluatedAt: "2025-09-12",
      totalScore: 88.4,
      nationalAverage: 71.2,
      domains: [
        { name: "기관운영", score: 82 },
        { name: "환경 및 안전", score: 94 },
        { name: "수급자권리보장", score: 90 },
        { name: "급여제공과정", score: 89 },
        { name: "급여제공결과", score: 85 },
      ],
    },
    programs: [
      { name: "미술치료", targetCount: 20, frequency: "주 2회", location: "프로그램실" },
      { name: "인지향상훈련", targetCount: 30, frequency: "매일", location: "프로그램실" },
      { name: "원예활동", targetCount: 15, frequency: "주 1회", location: "옥상정원" },
    ],
  },
  {
    id: "nh-002",
    name: "푸른솔요양원",
    facilityType: "NURSING_HOME",
    dataSource: "mock",
    gradeSource: "NHIS",
    grade: 2,
    address: "경기도 용인시 수지구 신봉로 88",
    lat: 37.3273,
    lng: 127.0987,
    phone: "031-555-0707",
    establishedYear: 2010,
    updatedAt: "2026-04-22",
    parking: { spots: 18, isFree: true },
    capacity: 100,
    currentOccupancy: 91,
    waitlistCount: 8,
    staff: {
      careWorkers: 50,
      nurses: 5,
      socialWorkers: 2,
      physicalTherapists: 1,
    },
    staffDetail: {
      administrative: { facilityHead: 1, officeManager: 1, staff: 3 },
      socialCare: { socialWorkers: 2, physicalTherapists: 1, occupationalTherapists: 0 },
      medical: { fullTimeDoctors: 0, partTimeDoctors: 1, nurses: 5, nursingAssistants: 3 },
    },
    roomTypes: ["4인실", "2인실"],
    facilityRooms: {
      bedrooms: { single: 0, double: 20, triple: 10, quad: 10, special: 0 },
      medical: { nursingRoom: 1, rehabRoom: 1 },
      dining: { diningRoom: 2, restroom: 8, bathroom: 3 },
    },
    nonCoveredFees: [
      { name: "식재료비(간식제외)", monthly: 420000, daily: 14000 },
      { name: "간식비용", monthly: 50000, daily: 1700 },
    ],
    evaluationDetail: {
      evaluatedAt: "2025-08-20",
      totalScore: 76.5,
      nationalAverage: 71.2,
      domains: [
        { name: "기관운영", score: 68 },
        { name: "환경 및 안전", score: 80 },
        { name: "수급자권리보장", score: 79 },
        { name: "급여제공과정", score: 78 },
        { name: "급여제공결과", score: 77 },
      ],
    },
    programs: [
      { name: "물리치료", targetCount: 40, frequency: "주 3회", location: "물리치료실" },
      { name: "레크리에이션", targetCount: 60, frequency: "주 1회", location: "다목적실" },
    ],
  },
  {
    id: "dnc-001",
    name: "햇살주야간보호센터",
    facilityType: "DAY_NIGHT_CARE",
    dataSource: "mock",
    gradeSource: "NHIS",
    grade: 1,
    address: "서울특별시 강남구 논현로 412",
    lat: 37.5087,
    lng: 127.0324,
    phone: "02-555-0808",
    establishedYear: 2017,
    updatedAt: "2026-06-05",
    parking: { spots: 8, isFree: true },
    capacity: 35,
    currentOccupancy: 30,
    waitlistCount: 0,
    staff: {
      careWorkers: 12,
      nurses: 2,
      socialWorkers: 1,
      physicalTherapists: 1,
    },
    staffDetail: {
      administrative: { facilityHead: 1, officeManager: 0, staff: 1 },
      socialCare: { socialWorkers: 1, physicalTherapists: 1, occupationalTherapists: 0 },
      medical: { fullTimeDoctors: 0, partTimeDoctors: 0, nurses: 2, nursingAssistants: 1 },
    },
    roomTypes: ["주간 프로그램실"],
    facilityRooms: {
      bedrooms: { single: 0, double: 0, triple: 0, quad: 0, special: 0 },
      medical: { nursingRoom: 1, rehabRoom: 1 },
      dining: { diningRoom: 1, restroom: 2, bathroom: 0 },
    },
    nonCoveredFees: [
      { name: "식재료비(간식제외)", monthly: 60000, daily: 2000 },
      { name: "간식비용", monthly: 30000, daily: 1000 },
    ],
    evaluationDetail: {
      evaluatedAt: "2025-10-04",
      totalScore: 85.8,
      nationalAverage: 63.7,
      domains: [
        { name: "기관운영", score: 69.7 },
        { name: "환경 및 안전", score: 96.6 },
        { name: "수급자권리보장", score: 87.5 },
        { name: "급여제공과정", score: 89.1 },
        { name: "급여제공결과", score: 82.3 },
      ],
    },
    programs: [
      { name: "공예활동", targetCount: 32, frequency: "회당 1시간", location: "생활실" },
      { name: "특화활동", targetCount: 32, frequency: "회당 1시간", location: "생활실" },
      { name: "노래교실", targetCount: 32, frequency: "회당 1시간", location: "프로그램실" },
    ],
  },
  {
    id: "hc-001",
    name: "다솜방문요양센터",
    facilityType: "HOME_CARE",
    dataSource: "mock",
    gradeSource: "NHIS",
    grade: null,
    address: "경기도 성남시 분당구 정자로 100",
    lat: 37.3654,
    lng: 127.1087,
    phone: "031-555-0909",
    establishedYear: 2019,
    updatedAt: "2026-05-30",
    capacity: 0,
    currentOccupancy: 0,
    waitlistCount: 0,
    staff: {
      careWorkers: 25,
      nurses: 1,
      socialWorkers: 1,
      physicalTherapists: 0,
    },
    staffDetail: {
      administrative: { facilityHead: 1, officeManager: 0, staff: 1 },
      socialCare: { socialWorkers: 1, physicalTherapists: 0, occupationalTherapists: 0 },
      medical: { fullTimeDoctors: 0, partTimeDoctors: 0, nurses: 1, nursingAssistants: 0 },
    },
    roomTypes: [],
    facilityRooms: {
      bedrooms: { single: 0, double: 0, triple: 0, quad: 0, special: 0 },
      medical: { nursingRoom: 0, rehabRoom: 0 },
      dining: { diningRoom: 0, restroom: 0, bathroom: 0 },
    },
    nonCoveredFees: [],
    programs: [],
  },
  {
    id: "st-001",
    name: "그린힐 실버타운",
    facilityType: "SILVER_TOWN",
    dataSource: "mock",
    gradeSource: "NHIS",
    grade: null,
    address: "경기도 남양주시 별내로 55",
    lat: 37.6398,
    lng: 127.0956,
    phone: "031-555-1010",
    establishedYear: 2020,
    updatedAt: "2026-06-20",
    parking: { spots: 60, isFree: true },
    capacity: 150,
    currentOccupancy: 120,
    waitlistCount: 0,
    staff: {
      careWorkers: 20,
      nurses: 4,
      socialWorkers: 3,
      physicalTherapists: 2,
    },
    staffDetail: {
      administrative: { facilityHead: 1, officeManager: 2, staff: 4 },
      socialCare: { socialWorkers: 3, physicalTherapists: 2, occupationalTherapists: 1 },
      medical: { fullTimeDoctors: 0, partTimeDoctors: 1, nurses: 4, nursingAssistants: 2 },
    },
    roomTypes: ["1인실", "부부실"],
    facilityRooms: {
      bedrooms: { single: 90, double: 30, triple: 0, quad: 0, special: 0 },
      medical: { nursingRoom: 1, rehabRoom: 1 },
      dining: { diningRoom: 2, restroom: 10, bathroom: 4 },
    },
    nonCoveredFees: [
      { name: "식비(3식)", monthly: 450000, daily: 15000 },
      { name: "관리비", monthly: 250000, daily: 0 },
    ],
    programs: [
      { name: "요가교실", targetCount: 25, frequency: "주 3회", location: "커뮤니티센터" },
      { name: "원예클럽", targetCount: 15, frequency: "주 1회", location: "옥상정원" },
    ],
  },
];

// NHIS 실데이터는 이제 lib/realNhisDataV2.json(전국 22,535건, longtermcare.or.kr 출처)을
// prisma/seed.ts에서 직접 읽어 DB에 시딩함 — 여기서는 데모 + HIRA(요양병원)만 유지.
export { DEMO_FACILITIES };
export const MOCK_FACILITIES: Facility[] = [...DEMO_FACILITIES, ...REAL_HIRA_FACILITIES];

export function getFacilityById(id: string): Facility | undefined {
  return MOCK_FACILITIES.find((f) => f.id === id);
}
